# Generated by Django 3.2.18 on 2023-04-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_post_portions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='portions',
            field=models.IntegerField(default=4),
        ),
    ]
