# Generated by Django 3.2.18 on 2023-04-21 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_post_portions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='portions',
        ),
    ]
